[package]
name = "aptos_dex"
version = "1.0.0"
authors = []

[addresses]
aptos_dex = "_"

[dependencies.AptosFramework]
#git = "https://github.com/aptos-labs/aptos-core.git"
#rev = "aptos-cli-v7.7.0"
#subdir = "aptos-move/framework/aptos-framework"
local = "../../aptos-core/aptos-move/framework/aptos-framework"

[dev-dependencies]

